import {StyleSheet} from 'react-native';

import {fonts} from '../../../../../infrustructure/theme/fonts';
import {colors} from '../../../../../infrustructure/theme/colors';
import {WP} from '../../../../../infrustructure/theme/responsive';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.background.main,
  },
  modalContainer: {
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  modalMainContainer: {
    paddingHorizontal: WP('4.5'),
    paddingTop: WP('4.5'),
    backgroundColor: colors.background.light,
  },
  modalContentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spacer: {
    width: 63,
    padding: WP('0.6'),
    backgroundColor: colors.disabled.light,
    borderRadius: 10,
    alignSelf: 'center',
  },
  cancelIconContainer: {
    width: WP('8'),
    height: WP('8'),
    backgroundColor: colors.disabled.light,
    borderRadius: WP('10'),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: WP('6'),
    right: WP('6'),
  },
  closeSheetStyle: {
    width: 36,
    height: 36,
  },
  listContainer: {
    width: WP('42'),
    padding: WP('3'),
    backgroundColor: '#B0B3BA19',
    borderRadius: 16,
    maxWidth: '100%',
    marginHorizontal: WP('2'),
    marginVertical: WP('2'),
  },
  vehicleContainer: {
    width: 36,
    height: 36,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4AD5940F',
    marginBottom: WP('2'),
  },
  vehicleImageStyle: {
    width: 17,
    height: 14,
    tintColor: colors.primary.main,
  },
  vehicleTextStyle: {
    fontFamily: fonts.soraMedium,
    fontSize: 16,
    color: colors.text.main,
    textAlign: 'left',
  },
  selectVehicleStyle: {
    fontFamily: fonts.soraBold,
    fontSize: 18,
    color: colors.text.main,
    textAlign: 'left',
    position: 'absolute',
    top: WP('13'),
    left: WP('7'),
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginHorizontal: WP('4'),
  },
  inputStyle: {
    borderRadius: 12,
  },
  emptyStyle: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  waitTextStyle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 18,
    color: colors.text.main,
    textAlign: 'center',
    marginTop: 10,
  },
  modalContainer2: {
    backgroundColor: '#F2F2F2',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  modalMainContainer2: {
    width: WP('100'),
    padding: WP('5'),
    backgroundColor: colors.background.light,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalContentContainer2: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spacer2: {
    width: 63,
    height: 6,
    backgroundColor: colors.disabled.light,
    borderRadius: 10,
    alignSelf: 'center',
  },
  cancelIconContainer2: {
    width: WP('8'),
    height: WP('8'),
    backgroundColor: colors.disabled.light,
    borderRadius: WP('10'),
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeSheetStyle2: {
    width: 36,
    height: 36,
  },
  listMainContainer: {
    maxWidth: '100%',
    position: 'relative',
  },
  listContainer2: {
    backgroundColor: colors.background.light,
    padding: WP('3'),
    marginTop: WP('5'),
    marginHorizontal: WP('5'),
    borderRadius: 13,
    flexDirection: 'row',
  },
  buttonContainer: {
    marginBottom: WP('5'),
    marginTop: WP('5'),
    width: WP('90'),
  },
  listContentContainer: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: '#4AD5940F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleImageStyle2: {
    width: 24,
    height: 19,
    tintColor: colors.primary.main,
  },
  listSecondContent: {
    marginLeft: WP('5'),
    maxWidth: '100%',
  },
  carModalTextStyle: {
    fontFamily: fonts.soraMedium,
    fontSize: 14,
    color: '#B0B3BA',
    textAlign: 'left',
  },
  plateTextStyle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 16,
    color: colors.text.main,
    textAlign: 'left',
  },
  carDetailContainer: {
    width: WP('50'),
    flexDirection: 'row',
    marginTop: WP('2'),
    marginBottom: WP('2'),
    alignItems: 'center',
    justifyContent: 'space-between',
    maxWidth: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#B0B3BA19',
  },
  carDetailContentContainer: {
    marginRight: WP('10'),
  },
  valueTextStyle: {
    fontFamily: fonts.soraBold,
    fontSize: 12,
    color: colors.text.main,
    textAlign: 'left',
  },
  nameTextStyle: {
    fontFamily: fonts.soraRegular,
    color: '#B0B3BA',
  },
  addVehicleContainer: {
    maxWidth: '100%',
    paddingHorizontal: WP('5'),
    paddingVertical: WP('1'),
    borderRadius: 16,
    borderColor: colors.primary.main,
    borderWidth: 1,
    borderStyle: 'dashed',
    marginHorizontal: WP('5'),
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: WP('5'),
  },
  addVehicleTextStyle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 16,
    color: colors.primary.main,
    flex: 1,
    textAlign: 'center',
  },
  listMainContainer3: {
    maxWidth: '100%',
    position: 'relative',
  },
  listContainer3: {
    backgroundColor: colors.background.light,
    padding: WP('3'),
    marginTop: WP('4'),
    marginLeft: WP('4'),
    borderRadius: 13,
    flexDirection: 'row',
    width: WP('88'),
  },
  listContentContainer3: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: '#4AD5940F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listIconStyle: {
    width: 24,
    height: 24,
    position: 'absolute',
    right: WP('4'),
    top: WP('4'),
  },
  listHeaderContainer: {
    maxWidth: '100%',
    marginHorizontal: WP('5'),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: WP('5'),
  },
  listHeaderTitle: {
    fontSize: 18,
    fontFamily: fonts.soraBold,
    color: colors.text.main,
  },
  listHeaderSubTitle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 16,
    color: colors.primary.main,
  },
  availableTextStyle: {
    fontFamily: fonts.soraBold,
    fontSize: 18,
    color: colors.text.main,
    textAlign: 'left',
    paddingTop: WP('7'),
    paddingHorizontal: WP('5'),
  },
  selectMoreTextStyle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 14,
    color: '#B0B3BA',
    textAlign: 'left',
    paddingHorizontal: WP('5'),
    marginBottom: WP('4'),
  },
  bookedButtonContainer: {
    width: WP('51'),
    marginTop: -40,
    marginLeft: WP('15'),
  },
  verifiedImageStyle: {
    width: 24,
    height: 24,
  },
  oilChangeTextStyle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 16,
    color: colors.text.main,
    textAlign: 'left',
    marginHorizontal: WP('2.5'),
  },
  startContainer: {
    maxWidth: '100%',
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  startTextStyle: {
    fontFamily: fonts.soraRegular,
    fontSize: 12,
    color: '#B0B3BA',
    textAlign: 'right',
    textAlignVertical: 'top',
  },
  srTextStyle: {
    fontFamily: fonts.soraMedium,
    fontSize: 16,
    color: colors.text.main,
    textAlign: 'right',
  },
  priceTextStyle: {
    fontFamily: fonts.soraBold,
  },
  selectServiceStyle: {
    textAlign: 'left',
    fontFamily: fonts.soraBold,
    fontSize: 18,
    color: colors.text.main,
    paddingTop: WP('7'),
    paddingHorizontal: WP('4'),
    marginBottom: WP('4'),
  },
  contentContainer: {
    width: WP('92'),
    padding: WP('4'),
    alignSelf: 'center',
    backgroundColor: colors.background.light,
    borderRadius: 13,
    flexDirection: 'row',
    paddingHorizontal: WP('5'),
  },
  subStyle: {
    width: 20,
    height: 20,
    tintColor: colors.primary.main,
    alignSelf: 'center',
  },
  serviceTypeContainer: {
    width: WP('76'),
    paddingHorizontal: WP('3'),
  },
  serviceTypeStyle: {
    textAlign: 'left',
    fontFamily: fonts.soraSemiBold,
    fontSize: 12,
    color: '#B0B3BA',
  },
  allServiceStyle: {
    fontFamily: fonts.soraBold,
    fontSize: 16,
    color: colors.text.main,
    textAlign: 'left',
  },
  arrowContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowUpStyle: {
    width: 7,
    height: 10,
  },
  footerContainer: {
    width: WP('100'),
    backgroundColor: colors.background.light,
    padding: WP('5'),
    flexDirection: 'row',
    borderTopColor: '#B8B9C133',
    borderTopWidth: 1,
    paddingTop: WP('13'),
    alignItems: 'center',
    paddingBottom: WP('10'),
  },
  footerContentContainer: {
    marginTop: WP(-10),
  },
  totalTextStyle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 16,
    color: '#B0B3BA',
    textAlign: 'left',
  },
  sarTextStyle: {
    fontFamily: fonts.soraRegular,
    fontSize: 20,
    color: colors.text.main,
    textAlign: 'left',
  },
  footerPriceText: {
    color: colors.primary.main,
    fontFamily: fonts.soraBold,
  },
  accordionContainer: {
    width: WP('92'),
    padding: WP('5'),
    backgroundColor: colors.background.light,
    alignSelf: 'center',
    borderRadius: 16,
    marginBottom: WP('3'),
    borderWidth: 1.5,
    borderColor: colors.primary.main,
  },
  accordionContentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  accordionSecondContent: {
    marginLeft: WP('8'),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 5,
  },
  listImageStyle: {
    width: 24,
    height: 24,
  },
  titleTextStyle: {
    fontFamily: fonts.soraSemiBold,
    fontSize: 16,
    color: colors.text.main,
    textAlign: 'left',
    marginHorizontal: WP(3),
    fontWeight: '500',
  },
  serviceTextStyle: {
    fontFamily: fonts.soraBold,
    fontSize: 18,
    color: colors.text.main,
    textAlign: 'left',
    marginHorizontal: WP('5'),
    fontWeight: '600',
  },
  listContainer4: {
    width: WP('92'),
    padding: WP('6'),
    backgroundColor: colors.background.light,
    borderRadius: 16,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: WP('3'),
  },
  listContentContainer4: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowStyle: {
    width: 13,
    height: 13,
  },
});

export {styles};
